### PR TITLE
Apply opacity and rotation to icon style

### PR DESCRIPTION
**Pull request by chrismayer**
This applies possible opacity and rotation values defined in the Mapbox style to the ``ol.style.Icon`` object.

The assignment is done outside the caching object (``iconImageCache``) by purpose to ensure an icon can be reused with different opacity and rotation values.

### CODE REVIEW

**Comment by ahocevar** [comment]
To clarify my above review comments: You'll want to add both properties to `functions.interpolated`, and then call `paint['icon-opacity'](zoom)` instead of just assigning `paint['icon-opacity']`

**Comment by chrismayer** [comment]
I feared that it isn't that easy 😉 

I had a look at the Mapbox GL Style spec. It seems that [icon-opacity](https://www.mapbox.com/mapbox-gl-style-spec/#paint-icon-opacity) and [icon-rotate](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-rotate) can only be numbers.  Am I missing anything regarding the "ramping functions"?

**Comment by chrismayer** [comment]
> Am I missing anything regarding the "ramping functions"?

Do you mean what is called "Zoom functions" [here](https://www.mapbox.com/mapbox-gl-style-spec/#types-function)?

**Comment by ahocevar** [comment]
Yes. See my clarification https://github.com/boundlessgeo/ol-mapbox-gl-style/pull/3#issuecomment-251643293 - it is actually very easy.

**Comment by chrismayer** [comment]
I just added another commit implementing the support for the ramping functions according to your suggestions in https://github.com/boundlessgeo/ol-mapbox-gl-style/pull/3#issuecomment-251643293. 

Would you have another look, please? Thanks!

**Comment by chrismayer** [comment]
> OpenLayers rotation is expected in radians

Right @ahocevar, good catch! I just changed this. Thanks for your multiple reviews.

**Pull request merged**
